services:
  simple-invoice:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: ${APP_VERSION:-$(cat VERSION)}
      tags:
        - ghcr.io/0dragosh/simple-invoice:develop
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - PORT=8080
      - DATA_DIR=/app/data
      - COMPANIES_HOUSE_API_KEY=${COMPANIES_HOUSE_API_KEY:-}
      - LOG_LEVEL=${LOG_LEVEL:-DEBUG}
    restart: unless-stopped

# Enable BuildKit by default for this compose file
x-setup:
  docker:
    buildkit: true 