name: E2E Tests

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true
          cache-dependency-path: "**/go.sum"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev
      
      - name: Create data directories
        run: mkdir -p data/images data/pdfs
      
      - name: Build Go app
        run: |
          go build -o app cmd/server/main.go
        env:
          CGO_ENABLED: 1
          GOOS: linux
          GOARCH: amd64

      - name: Start app server
        run: |
          ./app &
          # Wait for the server to start
          echo "Waiting for server to start..."
          sleep 10
          # Check if server is running
          curl -s http://localhost:8080/ > /dev/null
          if [ $? -eq 0 ]; then
            echo "Server is running at http://localhost:8080/"
          else
            echo "Failed to start server"
            exit 1
          fi
        env:
          DATA_DIR: ${{ github.workspace }}/data
          LOG_LEVEL: DEBUG

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: 'e2e/package-lock.json'
      
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('e2e/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      
      - name: Install Playwright and dependencies
        working-directory: e2e
        run: |
          npm ci
          npx playwright install chromium --with-deps
      
      - name: Create screenshots directory
        run: mkdir -p e2e/screenshots
      
      - name: Run Playwright tests
        working-directory: e2e
        run: |
          # Run all tests instead of just the simplified tests
          npx playwright test
        env:
          CI: true
          BASE_URL: http://localhost:8080
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report
          path: |
            e2e/playwright-report/
            e2e/test-results/
            e2e/screenshots/
          retention-days: 14
      
      - name: Upload generated PDFs
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: generated-pdfs
          path: |
            data/pdfs/
          retention-days: 14
