name: E2E Tests

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Install Go dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sqlite3 libsqlite3-dev
      
      - name: Create data directories
        run: mkdir -p data/images data/pdfs
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'e2e/package.json'
      
      - name: Install Playwright and dependencies
        working-directory: e2e
        run: |
          npm ci
          npx playwright install chromium --with-deps
      
      - name: Build app
        run: |
          go build -o simple-invoice cmd/server/main.go
      
      - name: Run Playwright tests
        working-directory: e2e
        run: |
          # Run tests
          npm run test:ci
        env:
          CI: true
          DATA_DIR: ${{ github.workspace }}/data
          LOG_LEVEL: DEBUG
      
      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            e2e/playwright-report/
            e2e/test-results/
          retention-days: 14
      
      - name: Upload generated PDFs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          path: |
            data/pdfs/
          retention-days: 14 